-- Ruleaza acest script in Supabase SQL Editor inainte de a publica formularele.

-- Permite panoului local sa citeasca rezervarile existente.
alter table public.rezervari enable row level security;
drop policy if exists "Panoul local poate citi rezervarile" on public.rezervari;
create policy "Panoul local poate citi rezervarile"
  on public.rezervari for select
  to anon, authenticated
  using (true);

create table if not exists public.mesaje_contact (
  id bigint generated by default as identity primary key,
  nume text not null,
  email text not null,
  telefon text,
  mesaj text not null,
  data timestamptz not null default now()
);

create table if not exists public.comenzi_must (
  id bigint generated by default as identity primary key,
  nume text not null,
  email text not null,
  telefon text,
  cantitate integer not null check (cantitate between 1 and 10),
  mesaj text,
  an_recolta integer not null,
  data timestamptz not null default now()
);

alter table public.mesaje_contact enable row level security;
alter table public.comenzi_must enable row level security;

drop policy if exists "Vizitatorii pot trimite mesaje" on public.mesaje_contact;
create policy "Vizitatorii pot trimite mesaje"
  on public.mesaje_contact for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Vizitatorii pot trimite comenzi de must" on public.comenzi_must;
create policy "Vizitatorii pot trimite comenzi de must"
  on public.comenzi_must for insert
  to anon, authenticated
  with check (true);

-- Necesara pentru panoul local rezervari.html, care citeste cu cheia publicabila.
-- Nu folosi aceasta politica daca panoul devine public; atunci trebuie adaugata autentificare Supabase.
drop policy if exists "Panoul local poate citi comenzile de must" on public.comenzi_must;
create policy "Panoul local poate citi comenzile de must"
  on public.comenzi_must for select
  to anon, authenticated
  using (true);